networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:
  minio_data: 

services:
  traefik:
    image: "traefik:v3.5.2"
    security_opt:
      - no-new-privileges:true
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  orderservice:
    build: .
    restart: unless-stopped
    command: [ "/app/ordersystem" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orders.entrypoints=web"
      - "traefik.http.services.orders.loadbalancer.server.port=3000"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGPORT=5432
      - DB_HOST=order-postgres
      - S3_ACCESS_KEY_ID=root
      - S3_SECRET_ACCESS_KEY=verysecret
      - S3_ENDPOINT=order-minio:8500
    networks:
      - intercom
      - web
    ports:
      - "3000:3000"

  sws:
    image: joseluisq/static-web-server:latest
    environment:
      - SERVER_PORT=80
      - SERVER_ROOT=/public
    volumes:
      - ./frontend:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=Host(`localhost`)"
      - "traefik.http.routers.sws.entrypoints=web"
    networks:
      - intercom
      - web

  order-postgres:
    image: postgres:18
    volumes:
      - order_pg_vol:/var/lib/postgresql
    restart: always
    networks:
      - intercom
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker


  order-minio:
    image: minio/minio:latest
    container_name: order-minio
    command: ["server", "--address", ":8500", "--console-address", ":8501", "/data"]
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=verysecret
    networks:
      - intercom
    ports:
      - "8500:8500"
      - "8501:8501"